export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED'

export const SET_SUCCESS = 'SET_SUCCESS'

export const SET_ERROR = 'SET_ERROR'

export const SET_REQUEST = 'SET_REQUEST'

export const CLEAR = 'CLEAR'
