export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED'

export const SET_SUCCESS = 'SET_SUCCESS'

export const SET_ERROR = 'SET_ERROR'

export const SET_REQUEST = 'SET_REQUEST'

export const SET_EMAIL = 'SET_EMAIL'

export const CLEAR = 'CLEAR'

export const SET_CONFIRMATION = 'SET_CONFIRMATION'

export const REMOVE_CONFIRMATION = 'REMOVE_CONFIRMATION'

export const SET_DRAWER = 'SET_DRAWER'

export const SET_PULL_TO_REFRESH_METHOD = 'SET_PULL_TO_REFRESH_METHOD'

export const SET_PULL_TO_LOAD_MORE_METHOD = 'SET_PULL_TO_LOAD_MORE_METHOD'
